language: emacs-lisp

env:
  matrix:
    - "EMACS=emacs24 ENSIME_TEST_SERVER_VERSION=2.10"

install:
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs23-gtk emacs23-el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi

script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "mkdir ~/.emacs.d"
  - "mkdir ~/.emacs.d/ensime-servers"
  - "mkdir ~/.emacs.d/ensime-servers/$ENSIME_TEST_SERVER_VERSION"
  - "touch ensime_test.log"
  - "$EMACS --version"
  - "$EMACS --batch --no-init-file --load .emacs_test.el --eval '(ensime-update-server \"$ENSIME_TEST_SERVER_VERSION\")'"
  - "$EMACS -d :99 --no-init-file --load .emacs_test.el --eval '(ensime-run-all-tests)' &"
  - "tail -f ensime_test.log"


  