before_install:
  - "export DISPLAY=:9.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "sudo apt-get install emacs"

script:
  - "mkdir frames"
  - "emacs -d :9 --no-init-file --load .emacs_test.el"