language: emacs-lisp

env:
  matrix:
#    - EMACS=emacs23
    - EMACS=emacs24

before_install:
  - "export DISPLAY=:9.0"
  - "sh -e /etc/init.d/xvfb start"


install:
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs23-gtk emacs23-el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi

script:
  - "$EMACS --version && $EMACS -d :9.0 --no-init-file --load .emacs_test.el"


  